apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: dev-md-0
  namespace: default
spec:
  clusterName: dev
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        env: dev
    spec:
      clusterName: dev
      bootstrap:
        configRef:
          name: dev-md-0
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: dev-md-0
        kind: DockerMachineTemplate