apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: vector
data:
  vector.yaml: |
    sources:
      kubernetes_logs:
        type: kubernetes_logs

    sinks:
      console:
        type: console
        inputs: ["kubernetes_logs"]
        encoding:
          codec: json