apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: demo
spec:
  rules:
    - host: hello.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80